using System.Runtime.InteropServices;using System.Text;
namespace LockKeyFlyout;
internal static unsafe class Native
{
    public const uint CS_DROPSHADOW=0x20000;public delegate nint WndProc(nint h,uint m,nint w,nint l);public delegate nint HookProc(int c,nint w,nint l);
    [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public struct WNDCLASSEX{public uint cbSize,style;public nint lpfnWndProc;public int cbClsExtra,cbWndExtra;public nint hInstance,hIcon,hCursor,hbrBackground,lpszMenuName;[MarshalAs(UnmanagedType.LPWStr)]public string lpszClassName;public nint hIconSm;}
    [StructLayout(LayoutKind.Sequential)]public struct MSG{public nint hwnd;public uint message;public nuint wParam;public nint lParam;public uint time;public POINT pt;}[StructLayout(LayoutKind.Sequential)]public struct POINT{public int x,y;}[StructLayout(LayoutKind.Sequential)]public struct RECT{public int left,top,right,bottom;}[StructLayout(LayoutKind.Sequential)]public struct MONITORINFO{public uint cbSize;public RECT rcMonitor,rcWork;public uint flags;}[StructLayout(LayoutKind.Sequential)]public struct PAINTSTRUCT{public nint hdc;public int fErase;public RECT rcPaint;public int fRestore,fIncUpdate;public fixed byte rgbReserved[32];}
    [StructLayout(LayoutKind.Sequential)]public struct ACCENT_POLICY{public int AccentState,AccentFlags;public uint GradientColor;public int AnimationId;}[StructLayout(LayoutKind.Sequential)]public struct WINDOWCOMPOSITIONATTRIBDATA{public int Attrib;public nint pvData;public int cbData;}
    [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public struct NOTIFYICONDATA{public uint cbSize;public nint hWnd;public uint uID,uFlags,uCallbackMessage;public nint hIcon;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=128)]public string szTip;public uint dwState,dwStateMask;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=256)]public string szInfo;public uint uTimeoutOrVersion;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=64)]public string szInfoTitle;public uint dwInfoFlags;public Guid guidItem;public nint hBalloonIcon;}
    [DllImport("kernel32",CharSet=CharSet.Unicode)]public static extern nint GetModuleHandle(string? s);[DllImport("user32",EntryPoint="RegisterClassExW",ExactSpelling=true)]public static extern ushort RegisterClassEx(ref WNDCLASSEX c);[DllImport("user32",EntryPoint="CreateWindowExW",ExactSpelling=true,CharSet=CharSet.Unicode)]public static extern nint CreateWindowEx(int ex,string cls,string text,int style,int x,int y,int w,int h,nint parent,nint menu,nint inst,nint p);[DllImport("user32",EntryPoint="DefWindowProcW",ExactSpelling=true)]public static extern nint DefWindowProc(nint h,uint m,nint w,nint l);[DllImport("user32",EntryPoint="GetMessageW",ExactSpelling=true)]public static extern int GetMessage(MSG* m,nint h,uint a,uint b);[DllImport("user32")]public static extern bool TranslateMessage(MSG* m);[DllImport("user32",EntryPoint="DispatchMessageW",ExactSpelling=true)]public static extern nint DispatchMessage(MSG* m);[DllImport("user32")]public static extern void PostQuitMessage(int c);[DllImport("user32")]public static extern bool PostMessage(nint h,uint m,nint w,nint l);
    [DllImport("user32")]public static extern nint SetWindowsHookEx(int id,HookProc p,nint mod,uint tid);[DllImport("user32")]public static extern bool UnhookWindowsHookEx(nint h);[DllImport("user32")]public static extern nint CallNextHookEx(nint h,int c,nint w,nint l);[DllImport("user32")]public static extern short GetKeyState(int k);
    [DllImport("user32")]public static extern bool ShowWindow(nint h,int c);[DllImport("user32")]public static extern bool UpdateWindow(nint h);[DllImport("user32")]public static extern bool DestroyWindow(nint h);[DllImport("user32")]public static extern bool SetWindowPos(nint h,nint after,int x,int y,int w,int he,uint f);[DllImport("user32")]public static extern bool SetLayeredWindowAttributes(nint h,uint c,byte a,uint f);[DllImport("user32")]public static extern nuint SetTimer(nint h,nuint id,uint ms,nint p);[DllImport("user32")]public static extern bool KillTimer(nint h,nuint id);[DllImport("user32")]public static extern bool InvalidateRect(nint h,nint r,bool e);[DllImport("user32")]public static extern uint GetDpiForWindow(nint h);
    [DllImport("user32")]public static extern bool GetCursorPos(POINT* p);[DllImport("user32")]public static extern nint MonitorFromPoint(POINT p,uint f);[DllImport("user32")]public static extern nint MonitorFromWindow(nint h,uint f);[DllImport("user32")]public static extern bool GetMonitorInfo(nint h,MONITORINFO* m);[DllImport("user32")]public static extern nint GetForegroundWindow();[DllImport("user32")]public static extern bool SetForegroundWindow(nint h);[DllImport("shcore")]public static extern int GetDpiForMonitor(nint monitor,int dpiType,out uint dpiX,out uint dpiY);
    [DllImport("user32")]public static extern nint BeginPaint(nint h,PAINTSTRUCT* p);[DllImport("user32")]public static extern bool EndPaint(nint h,PAINTSTRUCT* p);[DllImport("user32")]public static extern bool GetClientRect(nint h,RECT* r);[DllImport("user32")]public static extern int FillRect(nint d,RECT* r,nint b);[DllImport("gdi32")]public static extern nint CreateSolidBrush(uint c);[DllImport("gdi32")]public static extern bool DeleteObject(nint h);[DllImport("gdi32")]public static extern int SetBkMode(nint d,int m);[DllImport("gdi32")]public static extern uint SetTextColor(nint d,uint c);[DllImport("gdi32")]public static extern nint SelectObject(nint d,nint o);[DllImport("user32",CharSet=CharSet.Unicode)]public static extern int DrawText(nint d,string s,int n,RECT* r,uint f);[DllImport("gdi32",CharSet=CharSet.Unicode)]public static extern nint CreateFont(int h,int w,int e,int o,int weight,uint i,uint u,uint st,uint cs,uint op,uint cp,uint q,uint pitch,string face);
    [DllImport("gdi32")]public static extern nint CreatePen(int style,int width,uint color);[DllImport("gdi32")]public static extern nint GetStockObject(int index);[DllImport("gdi32")]public static extern bool RoundRect(nint dc,int left,int top,int right,int bottom,int width,int height);[DllImport("gdi32")]public static extern bool Arc(nint dc,int left,int top,int right,int bottom,int xr1,int yr1,int xr2,int yr2);[DllImport("gdi32")]public static extern bool Ellipse(nint dc,int left,int top,int right,int bottom);[DllImport("gdi32")]public static extern nint CreateRoundRectRgn(int left,int top,int right,int bottom,int width,int height);[DllImport("user32")]public static extern int SetWindowRgn(nint hwnd,nint region,bool redraw);
    [DllImport("gdi32")]public static extern bool PatBlt(nint dc,int x,int y,int width,int height,uint rop);
    [DllImport("shell32")]public static extern bool Shell_NotifyIcon(uint m,ref NOTIFYICONDATA d);[DllImport("user32")]public static extern nint CreatePopupMenu();[DllImport("user32",CharSet=CharSet.Unicode)]public static extern bool AppendMenu(nint h,uint f,nuint id,string? s);[DllImport("user32")]public static extern bool DestroyMenu(nint h);[DllImport("user32")]public static extern bool TrackPopupMenu(nint h,uint f,int x,int y,int r,nint w,nint p);[DllImport("user32")]public static extern nint LoadIcon(nint i,nint n);[DllImport("user32")]public static extern nint LoadCursor(nint i,nint n);
    [DllImport("user32")]public static extern nint SendMessage(nint h,uint m,nint w,nint l);[DllImport("user32")]public static extern nint GetDlgItem(nint h,int id);[DllImport("user32",CharSet=CharSet.Unicode)]public static extern int GetWindowText(nint h,StringBuilder b,int n);[DllImport("dwmapi")]public static extern int DwmSetWindowAttribute(nint h,int a,void* p,int n);
    [DllImport("user32",CharSet=CharSet.Unicode)]public static extern int MessageBox(nint h,string text,string caption,uint type);
    [DllImport("user32")]public static extern int SetWindowCompositionAttribute(nint hwnd,WINDOWCOMPOSITIONATTRIBDATA* data);
}
